inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Security/Eval:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Lint/InheritException:
  Enabled: false

Style/FileWrite:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/UnpackFirst:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/NilComparison:
  Enabled: false
