# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{clipboard}
  s.version = "0.9.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Lelis"]
  s.date = %q{2010-11-18}
  s.description = %q{Access the clipboard on all systems (Clipboard.copy & Clipboard.paste)}
  s.email = %q{mail@janlelis.de}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "clipboard.gemspec",
    "lib/clipboard.rb",
    "version.rb"
  ]
  s.homepage = %q{http://github.com/janlelis/clipboard}
  s.require_paths = ["lib"]
  s.requirements = ["on linux (or other X), you need xclip. Install it on debian/ubuntu with sudo apt-get install xclip"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Access the clipboard on all systems}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<zucker>, [">= 8"])
      s.add_runtime_dependency(%q<ffi>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<zucker>, [">= 8"])
      s.add_dependency(%q<ffi>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<zucker>, [">= 8"])
    s.add_dependency(%q<ffi>, [">= 0"])
  end
end

