name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Rubocop
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Run linter
      run: bundle exec rubocop .
